openapi: 3.0.0
info:
  version: '2018-06-29'
  x-release: v4
  title: AWS RoboMaker BatchDeleteWorlds ListWorldGenerationJobs API
  description: This section provides documentation for the AWS RoboMaker API operations.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: robomaker
  x-aws-signingName: robomaker
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/robomaker-2018-06-29.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://robomaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The RoboMaker multi-region endpoint
- url: https://robomaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The RoboMaker multi-region endpoint
- url: http://robomaker.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The RoboMaker endpoint for China (Beijing) and China (Ningxia)
- url: https://robomaker.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The RoboMaker endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: ListWorldGenerationJobs
paths:
  /listWorldGenerationJobs:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListWorldGenerationJobs
      description: Lists world generator jobs.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListWorldGenerationJobsResponse'
        '480':
          description: InvalidParameterException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterException'
        '481':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '482':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
      parameters:
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nextToken:
                  description: 'If the previous paginated request did not return all of the remaining results, the response object''s <code>nextToken</code> parameter value is set to a token. To retrieve the next set of results, call <code>ListWorldGenerationJobsRequest</code> again and assign that token to the request object''s <code>nextToken</code> parameter. If there are no remaining results, the previous response object''s NextToken parameter is set to null. '
                  type: string
                  pattern: '[a-zA-Z0-9_.\-\/+=]*'
                  minLength: 1
                  maxLength: 2048
                maxResults:
                  description: 'When this parameter is used, <code>ListWorldGeneratorJobs</code> only returns <code>maxResults</code> results in a single page along with a <code>nextToken</code> response element. The remaining results of the initial request can be seen by sending another <code>ListWorldGeneratorJobs</code> request with the returned <code>nextToken</code> value. This value can be between 1 and 100. If this parameter is not used, then <code>ListWorldGeneratorJobs</code> returns up to 100 results and a <code>nextToken</code> value if applicable. '
                  type: integer
                filters:
                  description: Optional filters to limit results. You can use <code>status</code> and <code>templateId</code>.
                  type: array
                  items:
                    $ref: '#/components/schemas/Filter'
                  minItems: 1
                  maxItems: 1
      tags:
      - ListWorldGenerationJobs
components:
  schemas:
    CreatedAt:
      type: string
      format: date-time
    Filter:
      type: object
      properties:
        name:
          allOf:
          - $ref: '#/components/schemas/Name'
          - description: The name of the filter.
        values:
          allOf:
          - $ref: '#/components/schemas/FilterValues'
          - description: A list of values.
      description: Information about a filter.
    ListWorldGenerationJobsResponse:
      type: object
      required:
      - worldGenerationJobSummaries
      properties:
        worldGenerationJobSummaries:
          allOf:
          - $ref: '#/components/schemas/WorldGenerationJobSummaries'
          - description: Summary information for world generator jobs.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: 'If the previous paginated request did not return all of the remaining results, the response object''s <code>nextToken</code> parameter value is set to a token. To retrieve the next set of results, call <code>ListWorldGeneratorJobsRequest</code> again and assign that token to the request object''s <code>nextToken</code> parameter. If there are no remaining results, the previous response object''s NextToken parameter is set to null. '
    WorldGenerationJobSummaries:
      type: array
      items:
        $ref: '#/components/schemas/WorldGenerationJobSummary'
      minItems: 0
      maxItems: 100
    WorldCount:
      type: object
      properties:
        floorplanCount:
          allOf:
          - $ref: '#/components/schemas/FloorplanCount'
          - description: The number of unique floorplans.
        interiorCountPerFloorplan:
          allOf:
          - $ref: '#/components/schemas/InteriorCountPerFloorplan'
          - description: The number of unique interiors per floorplan.
      description: <p>The number of worlds that will be created. You can configure the number of unique floorplans and the number of unique interiors for each floor plan. For example, if you want 1 world with 20 unique interiors, you set <code>floorplanCount = 1</code> and <code>interiorCountPerFloorplan = 20</code>. This will result in 20 worlds (<code>floorplanCount</code> * <code>interiorCountPerFloorplan)</code>. </p> <p>If you set <code>floorplanCount = 4</code> and <code>interiorCountPerFloorplan = 5</code>, there will be 20 worlds with 5 unique floor plans. </p>
    WorldGenerationJobStatus:
      type: string
      enum:
      - Pending
      - Running
      - Completed
      - Failed
      - PartialFailed
      - Canceling
      - Canceled
    Integer:
      type: integer
    WorldGenerationJobSummary:
      type: object
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The Amazon Resource Name (ARN) of the world generator job.
        template:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The Amazon Resource Name (arn) of the world template.
        createdAt:
          allOf:
          - $ref: '#/components/schemas/CreatedAt'
          - description: The time, in milliseconds since the epoch, when the world generator job was created.
        status:
          allOf:
          - $ref: '#/components/schemas/WorldGenerationJobStatus'
          - description: <p>The status of the world generator job:</p> <dl> <dt>Pending</dt> <dd> <p>The world generator job request is pending.</p> </dd> <dt>Running</dt> <dd> <p>The world generator job is running. </p> </dd> <dt>Completed</dt> <dd> <p>The world generator job completed. </p> </dd> <dt>Failed</dt> <dd> <p>The world generator job failed. See <code>failureCode</code> for more information. </p> </dd> <dt>PartialFailed</dt> <dd> <p>Some worlds did not generate.</p> </dd> <dt>Canceled</dt> <dd> <p>The world generator job was cancelled.</p> </dd> <dt>Canceling</dt> <dd> <p>The world generator job is being cancelled.</p> </dd> </dl>
        worldCount:
          allOf:
          - $ref: '#/components/schemas/WorldCount'
          - description: Information about the world count.
        succeededWorldCount:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The number of worlds that were generated.
        failedWorldCount:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The number of worlds that failed.
      description: Information about a world generator job.
    Arn:
      type: string
      pattern: arn:.*
      minLength: 1
      maxLength: 1224
    InvalidParameterException: {}
    FloorplanCount:
      type: integer
    InternalServerException: {}
    Name:
      type: string
      pattern: '[a-zA-Z0-9_\-]*'
      minLength: 1
      maxLength: 255
    FilterValues:
      type: array
      items:
        $ref: '#/components/schemas/Name'
      minItems: 1
      maxItems: 1
    PaginationToken:
      type: string
      pattern: '[a-zA-Z0-9_.\-\/+=]*'
      minLength: 1
      maxLength: 2048
    ThrottlingException: {}
    InteriorCountPerFloorplan:
      type: integer
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/robomaker/
x-hasEquivalentPaths: true
