openapi: 3.2.0
info:
  version: 1.0.0
  x-release: v4
  title: AWS RoboMaker BatchDeleteWorlds List Simulation Job Batches API
  description: This section provides documentation for the AWS RoboMaker API operations.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: robomaker
  x-aws-signingName: robomaker
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/robomaker-2018-06-29.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://robomaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The RoboMaker multi-region endpoint
- url: https://robomaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The RoboMaker multi-region endpoint
- url: http://robomaker.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The RoboMaker endpoint for China (Beijing) and China (Ningxia)
- url: https://robomaker.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The RoboMaker endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: ListSimulationJobBatches
paths:
  /listSimulationJobBatches:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListSimulationJobBatches
      description: 'Returns a list simulation job batches. You can optionally provide filters to retrieve specific simulation batch jobs. '
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListSimulationJobBatchesResponse'
        '480':
          description: InvalidParameterException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterException'
        '481':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
      parameters:
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nextToken:
                  description: 'If the previous paginated request did not return all of the remaining results, the response object''s <code>nextToken</code> parameter value is set to a token. To retrieve the next set of results, call <code>ListSimulationJobBatches</code> again and assign that token to the request object''s <code>nextToken</code> parameter. If there are no remaining results, the previous response object''s NextToken parameter is set to null. '
                  type: string
                  pattern: '[a-zA-Z0-9_.\-\/+=]*'
                  minLength: 1
                  maxLength: 2048
                maxResults:
                  description: 'When this parameter is used, <code>ListSimulationJobBatches</code> only returns <code>maxResults</code> results in a single page along with a <code>nextToken</code> response element. The remaining results of the initial request can be seen by sending another <code>ListSimulationJobBatches</code> request with the returned <code>nextToken</code> value. '
                  type: integer
                filters:
                  description: Optional filters to limit results.
                  type: array
                  items:
                    $ref: '#/components/schemas/Filter'
                  minItems: 1
                  maxItems: 1
      tags:
      - ListSimulationJobBatches
components:
  schemas:
    SimulationJobBatchSummary:
      type: object
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The Amazon Resource Name (ARN) of the batch.
        lastUpdatedAt:
          allOf:
          - $ref: '#/components/schemas/LastUpdatedAt'
          - description: The time, in milliseconds since the epoch, when the simulation job batch was last updated.
        createdAt:
          allOf:
          - $ref: '#/components/schemas/CreatedAt'
          - description: The time, in milliseconds since the epoch, when the simulation job batch was created.
        status:
          allOf:
          - $ref: '#/components/schemas/SimulationJobBatchStatus'
          - description: <p>The status of the simulation job batch.</p> <dl> <dt>Pending</dt> <dd> <p>The simulation job batch request is pending.</p> </dd> <dt>InProgress</dt> <dd> <p>The simulation job batch is in progress. </p> </dd> <dt>Failed</dt> <dd> <p>The simulation job batch failed. One or more simulation job requests could not be completed due to an internal failure (like <code>InternalServiceError</code>). See <code>failureCode</code> and <code>failureReason</code> for more information.</p> </dd> <dt>Completed</dt> <dd> <p>The simulation batch job completed. A batch is complete when (1) there are no pending simulation job requests in the batch and none of the failed simulation job requests are due to <code>InternalServiceError</code> and (2) when all created simulation jobs have reached a terminal state (for example, <code>Completed</code> or <code>Failed</code>). </p> </dd> <dt>Canceled</dt> <dd> <p>The simulation batch job was cancelled.</p> </dd> <dt>Canceling</dt> <dd> <p>The simulation batch job is being cancelled.</p> </dd> <dt>Completing</dt> <dd> <p>The simulation batch job is completing.</p> </dd> <dt>TimingOut</dt> <dd> <p>The simulation job batch is timing out.</p> <p>If a batch timing out, and there are pending requests that were failing due to an internal failure (like <code>InternalServiceError</code>), the batch status will be <code>Failed</code>. If there are no such failing request, the batch status will be <code>TimedOut</code>. </p> </dd> <dt>TimedOut</dt> <dd> <p>The simulation batch job timed out.</p> </dd> </dl>
        failedRequestCount:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The number of failed simulation job requests.
        pendingRequestCount:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The number of pending simulation job requests.
        createdRequestCount:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The number of created simulation job requests.
      description: Information about a simulation job batch.
    InternalServerException: {}
    SimulationJobBatchSummaries:
      type: array
      items:
        $ref: '#/components/schemas/SimulationJobBatchSummary'
    SimulationJobBatchStatus:
      type: string
      enum:
      - Pending
      - InProgress
      - Failed
      - Completed
      - Canceled
      - Canceling
      - Completing
      - TimingOut
      - TimedOut
    InvalidParameterException: {}
    Name:
      type: string
      pattern: '[a-zA-Z0-9_\-]*'
      minLength: 1
      maxLength: 255
    CreatedAt:
      type: string
      format: date-time
    PaginationToken:
      type: string
      pattern: '[a-zA-Z0-9_.\-\/+=]*'
      minLength: 1
      maxLength: 2048
    Arn:
      type: string
      pattern: arn:.*
      minLength: 1
      maxLength: 1224
    FilterValues:
      type: array
      items:
        $ref: '#/components/schemas/Name'
      minItems: 1
      maxItems: 1
    ListSimulationJobBatchesResponse:
      type: object
      properties:
        simulationJobBatchSummaries:
          allOf:
          - $ref: '#/components/schemas/SimulationJobBatchSummaries'
          - description: A list of simulation job batch summaries.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: 'If the previous paginated request did not return all of the remaining results, the response object''s <code>nextToken</code> parameter value is set to a token. To retrieve the next set of results, call <code>ListSimulationJobBatches</code> again and assign that token to the request object''s <code>nextToken</code> parameter. If there are no remaining results, the previous response object''s NextToken parameter is set to null. '
    LastUpdatedAt:
      type: string
      format: date-time
    Filter:
      type: object
      properties:
        name:
          allOf:
          - $ref: '#/components/schemas/Name'
          - description: The name of the filter.
        values:
          allOf:
          - $ref: '#/components/schemas/FilterValues'
          - description: A list of values.
      description: Information about a filter.
    Integer:
      type: integer
  parameters:
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/robomaker/
x-hasEquivalentPaths: true
