openapi: 3.0.0
info:
  version: '2018-06-29'
  x-release: v4
  title: AWS RoboMaker BatchDeleteWorlds ListRobots API
  description: This section provides documentation for the AWS RoboMaker API operations.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: robomaker
  x-aws-signingName: robomaker
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/robomaker-2018-06-29.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://robomaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The RoboMaker multi-region endpoint
- url: https://robomaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The RoboMaker multi-region endpoint
- url: http://robomaker.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The RoboMaker endpoint for China (Beijing) and China (Ningxia)
- url: https://robomaker.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The RoboMaker endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: ListRobots
paths:
  /listRobots:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      deprecated: true
      operationId: ListRobots
      description: <p>Returns a list of robots. You can optionally provide filters to retrieve specific robots.</p> <important> <p>This API will no longer be supported as of May 2, 2022. Use it to remove resources that were created for Deployment Service.</p> </important>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListRobotsResponse'
        '480':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '481':
          description: InvalidParameterException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterException'
        '482':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '483':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
      parameters:
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nextToken:
                  description: 'If the previous paginated request did not return all of the remaining results, the response object''s <code>nextToken</code> parameter value is set to a token. To retrieve the next set of results, call <code>ListRobots</code> again and assign that token to the request object''s <code>nextToken</code> parameter. If there are no remaining results, the previous response object''s NextToken parameter is set to null. '
                  type: string
                  pattern: '[a-zA-Z0-9_.\-\/+=]*'
                  minLength: 1
                  maxLength: 2048
                maxResults:
                  description: 'When this parameter is used, <code>ListRobots</code> only returns <code>maxResults</code> results in a single page along with a <code>nextToken</code> response element. The remaining results of the initial request can be seen by sending another <code>ListRobots</code> request with the returned <code>nextToken</code> value. This value can be between 1 and 200. If this parameter is not used, then <code>ListRobots</code> returns up to 200 results and a <code>nextToken</code> value if applicable. '
                  type: integer
                filters:
                  description: <p>Optional filters to limit results.</p> <p>The filter names <code>status</code> and <code>fleetName</code> are supported. When filtering, you must use the complete value of the filtered item. You can use up to three filters, but they must be for the same named item. For example, if you are looking for items with the status <code>Registered</code> or the status <code>Available</code>.</p>
                  type: array
                  items:
                    $ref: '#/components/schemas/Filter'
                  minItems: 1
                  maxItems: 1
      tags:
      - ListRobots
components:
  schemas:
    CreatedAt:
      type: string
      format: date-time
    Filter:
      type: object
      properties:
        name:
          allOf:
          - $ref: '#/components/schemas/Name'
          - description: The name of the filter.
        values:
          allOf:
          - $ref: '#/components/schemas/FilterValues'
          - description: A list of values.
      description: Information about a filter.
    Robots:
      type: array
      items:
        $ref: '#/components/schemas/Robot'
      minItems: 0
      maxItems: 1000
    RobotStatus:
      type: string
      enum:
      - Available
      - Registered
      - PendingNewDeployment
      - Deploying
      - Failed
      - InSync
      - NoResponse
    Id:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 1224
    Architecture:
      type: string
      enum:
      - X86_64
      - ARM64
      - ARMHF
    Arn:
      type: string
      pattern: arn:.*
      minLength: 1
      maxLength: 1224
    InvalidParameterException: {}
    InternalServerException: {}
    Name:
      type: string
      pattern: '[a-zA-Z0-9_\-]*'
      minLength: 1
      maxLength: 255
    ListRobotsResponse:
      type: object
      deprecated: true
      properties:
        robots:
          allOf:
          - $ref: '#/components/schemas/Robots'
          - description: A list of robots that meet the criteria of the request.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: 'If the previous paginated request did not return all of the remaining results, the response object''s <code>nextToken</code> parameter value is set to a token. To retrieve the next set of results, call <code>ListRobots</code> again and assign that token to the request object''s <code>nextToken</code> parameter. If there are no remaining results, the previous response object''s NextToken parameter is set to null. '
      description: Support for the AWS RoboMaker application deployment feature has ended. For additional information, see https://docs.aws.amazon.com/robomaker/latest/dg/fleets.html.
    FilterValues:
      type: array
      items:
        $ref: '#/components/schemas/Name'
      minItems: 1
      maxItems: 1
    PaginationToken:
      type: string
      pattern: '[a-zA-Z0-9_.\-\/+=]*'
      minLength: 1
      maxLength: 2048
    Robot:
      type: object
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The Amazon Resource Name (ARN) of the robot.
        name:
          allOf:
          - $ref: '#/components/schemas/Name'
          - description: The name of the robot.
        fleetArn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The Amazon Resource Name (ARN) of the fleet.
        status:
          allOf:
          - $ref: '#/components/schemas/RobotStatus'
          - description: The status of the robot.
        greenGrassGroupId:
          allOf:
          - $ref: '#/components/schemas/Id'
          - description: The Greengrass group associated with the robot.
        createdAt:
          allOf:
          - $ref: '#/components/schemas/CreatedAt'
          - description: The time, in milliseconds since the epoch, when the robot was created.
        architecture:
          allOf:
          - $ref: '#/components/schemas/Architecture'
          - description: The architecture of the robot.
        lastDeploymentJob:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The Amazon Resource Name (ARN) of the last deployment job.
        lastDeploymentTime:
          allOf:
          - $ref: '#/components/schemas/CreatedAt'
          - description: The time of the last deployment.
      description: Information about a robot.
    ThrottlingException: {}
    ResourceNotFoundException: {}
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/robomaker/
x-hasEquivalentPaths: true
