openapi: 3.0.0
info:
  version: '2018-06-29'
  x-release: v4
  title: AWS RoboMaker BatchDeleteWorlds DescribeWorldGenerationJob API
  description: This section provides documentation for the AWS RoboMaker API operations.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: robomaker
  x-aws-signingName: robomaker
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/robomaker-2018-06-29.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://robomaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The RoboMaker multi-region endpoint
- url: https://robomaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The RoboMaker multi-region endpoint
- url: http://robomaker.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The RoboMaker endpoint for China (Beijing) and China (Ningxia)
- url: https://robomaker.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The RoboMaker endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: DescribeWorldGenerationJob
paths:
  /describeWorldGenerationJob:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DescribeWorldGenerationJob
      description: Describes a world generation job.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DescribeWorldGenerationJobResponse'
        '480':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '481':
          description: InvalidParameterException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterException'
        '482':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '483':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - job
              properties:
                job:
                  description: The Amazon Resource Name (arn) of the world generation job to describe.
                  type: string
                  pattern: arn:.*
                  minLength: 1
                  maxLength: 1224
      tags:
      - DescribeWorldGenerationJob
components:
  schemas:
    CreatedAt:
      type: string
      format: date-time
    TagMap:
      type: object
      minProperties: 0
      maxProperties: 50
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    ClientRequestToken:
      type: string
      pattern: '[a-zA-Z0-9_\-=]*'
      minLength: 1
      maxLength: 64
    WorldFailure:
      type: object
      properties:
        failureCode:
          allOf:
          - $ref: '#/components/schemas/WorldGenerationJobErrorCode'
          - description: <p>The failure code of the world export job if it failed:</p> <dl> <dt>InternalServiceError</dt> <dd> <p>Internal service error.</p> </dd> <dt>LimitExceeded</dt> <dd> <p>The requested resource exceeds the maximum number allowed, or the number of concurrent stream requests exceeds the maximum number allowed. </p> </dd> <dt>ResourceNotFound</dt> <dd> <p>The specified resource could not be found. </p> </dd> <dt>RequestThrottled</dt> <dd> <p>The request was throttled.</p> </dd> <dt>InvalidInput</dt> <dd> <p>An input parameter in the request is not valid.</p> </dd> </dl>
        sampleFailureReason:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: 'The sample reason why the world failed. World errors are aggregated. A sample is used as the <code>sampleFailureReason</code>. '
        failureCount:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The number of failed worlds.
      description: Information about a failed world.
    FailureSummary:
      type: object
      properties:
        totalFailureCount:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The total number of failures.
        failures:
          allOf:
          - $ref: '#/components/schemas/WorldFailures'
          - description: The worlds that failed.
      description: Information about worlds that failed.
    WorldCount:
      type: object
      properties:
        floorplanCount:
          allOf:
          - $ref: '#/components/schemas/FloorplanCount'
          - description: The number of unique floorplans.
        interiorCountPerFloorplan:
          allOf:
          - $ref: '#/components/schemas/InteriorCountPerFloorplan'
          - description: The number of unique interiors per floorplan.
      description: <p>The number of worlds that will be created. You can configure the number of unique floorplans and the number of unique interiors for each floor plan. For example, if you want 1 world with 20 unique interiors, you set <code>floorplanCount = 1</code> and <code>interiorCountPerFloorplan = 20</code>. This will result in 20 worlds (<code>floorplanCount</code> * <code>interiorCountPerFloorplan)</code>. </p> <p>If you set <code>floorplanCount = 4</code> and <code>interiorCountPerFloorplan = 5</code>, there will be 20 worlds with 5 unique floor plans. </p>
    TagValue:
      type: string
      pattern: '[a-zA-Z0-9 _.\-\/+=:]*'
      minLength: 0
      maxLength: 256
    Arns:
      type: array
      items:
        $ref: '#/components/schemas/Arn'
      minItems: 1
      maxItems: 100
    DescribeWorldGenerationJobResponse:
      type: object
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The Amazon Resource Name (ARN) of the world generation job.
        status:
          allOf:
          - $ref: '#/components/schemas/WorldGenerationJobStatus'
          - description: <p>The status of the world generation job:</p> <dl> <dt>Pending</dt> <dd> <p>The world generation job request is pending.</p> </dd> <dt>Running</dt> <dd> <p>The world generation job is running. </p> </dd> <dt>Completed</dt> <dd> <p>The world generation job completed. </p> </dd> <dt>Failed</dt> <dd> <p>The world generation job failed. See <code>failureCode</code> for more information. </p> </dd> <dt>PartialFailed</dt> <dd> <p>Some worlds did not generate.</p> </dd> <dt>Canceled</dt> <dd> <p>The world generation job was cancelled.</p> </dd> <dt>Canceling</dt> <dd> <p>The world generation job is being cancelled.</p> </dd> </dl>
        createdAt:
          allOf:
          - $ref: '#/components/schemas/CreatedAt'
          - description: The time, in milliseconds since the epoch, when the world generation job was created.
        failureCode:
          allOf:
          - $ref: '#/components/schemas/WorldGenerationJobErrorCode'
          - description: <p>The failure code of the world generation job if it failed:</p> <dl> <dt>InternalServiceError</dt> <dd> <p>Internal service error.</p> </dd> <dt>LimitExceeded</dt> <dd> <p>The requested resource exceeds the maximum number allowed, or the number of concurrent stream requests exceeds the maximum number allowed. </p> </dd> <dt>ResourceNotFound</dt> <dd> <p>The specified resource could not be found. </p> </dd> <dt>RequestThrottled</dt> <dd> <p>The request was throttled.</p> </dd> <dt>InvalidInput</dt> <dd> <p>An input parameter in the request is not valid.</p> </dd> </dl>
        failureReason:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: The reason why the world generation job failed.
        clientRequestToken:
          allOf:
          - $ref: '#/components/schemas/ClientRequestToken'
          - description: Unique, case-sensitive identifier that you provide to ensure the idempotency of the request.
        template:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The Amazon Resource Name (arn) of the world template.
        worldCount:
          allOf:
          - $ref: '#/components/schemas/WorldCount'
          - description: Information about the world count.
        finishedWorldsSummary:
          allOf:
          - $ref: '#/components/schemas/FinishedWorldsSummary'
          - description: Summary information about finished worlds.
        tags:
          allOf:
          - $ref: '#/components/schemas/TagMap'
          - description: A map that contains tag keys and tag values that are attached to the world generation job.
        worldTags:
          allOf:
          - $ref: '#/components/schemas/TagMap'
          - description: A map that contains tag keys and tag values that are attached to the generated worlds.
    FinishedWorldsSummary:
      type: object
      properties:
        finishedCount:
          allOf:
          - $ref: '#/components/schemas/Integer'
          - description: The total number of finished worlds.
        succeededWorlds:
          allOf:
          - $ref: '#/components/schemas/Arns'
          - description: A list of worlds that succeeded.
        failureSummary:
          allOf:
          - $ref: '#/components/schemas/FailureSummary'
          - description: Information about worlds that failed.
      description: Information about worlds that finished.
    WorldFailures:
      type: array
      items:
        $ref: '#/components/schemas/WorldFailure'
      minItems: 0
      maxItems: 100
    WorldGenerationJobStatus:
      type: string
      enum:
      - Pending
      - Running
      - Completed
      - Failed
      - PartialFailed
      - Canceling
      - Canceled
    Integer:
      type: integer
    Arn:
      type: string
      pattern: arn:.*
      minLength: 1
      maxLength: 1224
    InvalidParameterException: {}
    FloorplanCount:
      type: integer
    WorldGenerationJobErrorCode:
      type: string
      enum:
      - InternalServiceError
      - LimitExceeded
      - ResourceNotFound
      - RequestThrottled
      - InvalidInput
      - AllWorldGenerationFailed
    InternalServerException: {}
    GenericString:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 1024
    ThrottlingException: {}
    InteriorCountPerFloorplan:
      type: integer
    ResourceNotFoundException: {}
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/robomaker/
x-hasEquivalentPaths: true
