openapi: 3.0.0
info:
  version: '2018-06-29'
  x-release: v4
  title: AWS RoboMaker BatchDeleteWorlds SyncDeploymentJob API
  description: This section provides documentation for the AWS RoboMaker API operations.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: robomaker
  x-aws-signingName: robomaker
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/robomaker-2018-06-29.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://robomaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The RoboMaker multi-region endpoint
- url: https://robomaker.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The RoboMaker multi-region endpoint
- url: http://robomaker.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The RoboMaker endpoint for China (Beijing) and China (Ningxia)
- url: https://robomaker.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The RoboMaker endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: SyncDeploymentJob
paths:
  /syncDeploymentJob:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      deprecated: true
      operationId: SyncDeploymentJob
      description: <p>Syncrhonizes robots in a fleet to the latest deployment. This is helpful if robots were added after a deployment.</p> <important> <p>This API will no longer be supported as of May 2, 2022. Use it to remove resources that were created for Deployment Service.</p> </important>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyncDeploymentJobResponse'
        '480':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '481':
          description: InvalidParameterException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidParameterException'
        '482':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '483':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '484':
          description: LimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LimitExceededException'
        '485':
          description: ConcurrentDeploymentException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcurrentDeploymentException'
        '486':
          description: IdempotentParameterMismatchException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdempotentParameterMismatchException'
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - clientRequestToken
              - fleet
              properties:
                clientRequestToken:
                  description: Unique, case-sensitive identifier that you provide to ensure the idempotency of the request.
                  type: string
                  pattern: '[a-zA-Z0-9_\-=]*'
                  minLength: 1
                  maxLength: 64
                fleet:
                  description: The target fleet for the synchronization.
                  type: string
                  pattern: arn:.*
                  minLength: 1
                  maxLength: 1224
      tags:
      - SyncDeploymentJob
components:
  schemas:
    CreatedAt:
      type: string
      format: date-time
    DeploymentApplicationConfig:
      type: object
      required:
      - application
      - applicationVersion
      - launchConfig
      properties:
        application:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The Amazon Resource Name (ARN) of the robot application.
        applicationVersion:
          allOf:
          - $ref: '#/components/schemas/DeploymentVersion'
          - description: The version of the application.
        launchConfig:
          allOf:
          - $ref: '#/components/schemas/DeploymentLaunchConfig'
          - description: The launch configuration.
      description: Information about a deployment application configuration.
    Path:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 1024
    S3Etag:
      type: string
    DeploymentVersion:
      type: string
      pattern: '[0-9]*'
      minLength: 1
      maxLength: 255
    DeploymentJobErrorCode:
      type: string
      enum:
      - ResourceNotFound
      - EnvironmentSetupError
      - EtagMismatch
      - FailureThresholdBreached
      - RobotDeploymentAborted
      - RobotDeploymentNoResponse
      - RobotAgentConnectionTimeout
      - GreengrassDeploymentFailed
      - InvalidGreengrassGroup
      - MissingRobotArchitecture
      - MissingRobotApplicationArchitecture
      - MissingRobotDeploymentResource
      - GreengrassGroupVersionDoesNotExist
      - LambdaDeleted
      - ExtractingBundleFailure
      - PreLaunchFileFailure
      - PostLaunchFileFailure
      - BadPermissionError
      - DownloadConditionFailed
      - BadLambdaAssociated
      - InternalServerError
      - RobotApplicationDoesNotExist
      - DeploymentFleetDoesNotExist
      - FleetDeploymentTimeout
    DeploymentConfig:
      type: object
      properties:
        concurrentDeploymentPercentage:
          allOf:
          - $ref: '#/components/schemas/Percentage'
          - description: The percentage of robots receiving the deployment at the same time.
        failureThresholdPercentage:
          allOf:
          - $ref: '#/components/schemas/Percentage'
          - description: The percentage of deployments that need to fail before stopping deployment.
        robotDeploymentTimeoutInSeconds:
          allOf:
          - $ref: '#/components/schemas/DeploymentTimeout'
          - description: The amount of time, in seconds, to wait for deployment to a single robot to complete. Choose a time between 1 minute and 7 days. The default is 5 hours.
        downloadConditionFile:
          allOf:
          - $ref: '#/components/schemas/S3Object'
          - description: The download condition file.
      description: Information about a deployment configuration.
    Command:
      type: string
      pattern: '[a-zA-Z0-9_.\-]*'
      minLength: 1
      maxLength: 1024
    DeploymentTimeout:
      type: integer
    LimitExceededException: {}
    S3Object:
      type: object
      required:
      - bucket
      - key
      properties:
        bucket:
          allOf:
          - $ref: '#/components/schemas/S3Bucket'
          - description: The bucket containing the object.
        key:
          allOf:
          - $ref: '#/components/schemas/S3Key'
          - description: The key of the object.
        etag:
          allOf:
          - $ref: '#/components/schemas/S3Etag'
          - description: The etag of the object.
      description: Information about an S3 object.
    Arn:
      type: string
      pattern: arn:.*
      minLength: 1
      maxLength: 1224
    DeploymentStatus:
      type: string
      enum:
      - Pending
      - Preparing
      - InProgress
      - Failed
      - Succeeded
      - Canceled
    InvalidParameterException: {}
    S3Bucket:
      type: string
      pattern: '[a-z0-9][a-z0-9.\-]*[a-z0-9]'
      minLength: 3
      maxLength: 63
    Percentage:
      type: integer
      minimum: 1
      maximum: 100
    IdempotentParameterMismatchException: {}
    EnvironmentVariableValue:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 1024
    ConcurrentDeploymentException: {}
    S3Key:
      type: string
      pattern: .*
      minLength: 1
      maxLength: 1024
    DeploymentLaunchConfig:
      type: object
      required:
      - packageName
      - launchFile
      properties:
        packageName:
          allOf:
          - $ref: '#/components/schemas/Command'
          - description: The package name.
        preLaunchFile:
          allOf:
          - $ref: '#/components/schemas/Path'
          - description: The deployment pre-launch file. This file will be executed prior to the launch file.
        launchFile:
          allOf:
          - $ref: '#/components/schemas/Command'
          - description: The launch file name.
        postLaunchFile:
          allOf:
          - $ref: '#/components/schemas/Path'
          - description: The deployment post-launch file. This file will be executed after the launch file.
        environmentVariables:
          allOf:
          - $ref: '#/components/schemas/EnvironmentVariableMap'
          - description: An array of key/value pairs specifying environment variables for the robot application
      description: Configuration information for a deployment launch.
    InternalServerException: {}
    SyncDeploymentJobResponse:
      type: object
      deprecated: true
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The Amazon Resource Name (ARN) of the synchronization request.
        fleet:
          allOf:
          - $ref: '#/components/schemas/Arn'
          - description: The Amazon Resource Name (ARN) of the fleet.
        status:
          allOf:
          - $ref: '#/components/schemas/DeploymentStatus'
          - description: The status of the synchronization job.
        deploymentConfig:
          allOf:
          - $ref: '#/components/schemas/DeploymentConfig'
          - description: Information about the deployment configuration.
        deploymentApplicationConfigs:
          allOf:
          - $ref: '#/components/schemas/DeploymentApplicationConfigs'
          - description: Information about the deployment application configurations.
        failureReason:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: The failure reason if the job fails.
        failureCode:
          allOf:
          - $ref: '#/components/schemas/DeploymentJobErrorCode'
          - description: <p>The failure code if the job fails:</p> <dl> <dt>InternalServiceError</dt> <dd> <p>Internal service error.</p> </dd> <dt>RobotApplicationCrash</dt> <dd> <p>Robot application exited abnormally.</p> </dd> <dt>SimulationApplicationCrash</dt> <dd> <p> Simulation application exited abnormally.</p> </dd> <dt>BadPermissionsRobotApplication</dt> <dd> <p>Robot application bundle could not be downloaded.</p> </dd> <dt>BadPermissionsSimulationApplication</dt> <dd> <p>Simulation application bundle could not be downloaded.</p> </dd> <dt>BadPermissionsS3Output</dt> <dd> <p>Unable to publish outputs to customer-provided S3 bucket.</p> </dd> <dt>BadPermissionsCloudwatchLogs</dt> <dd> <p>Unable to publish logs to customer-provided CloudWatch Logs resource.</p> </dd> <dt>SubnetIpLimitExceeded</dt> <dd> <p>Subnet IP limit exceeded.</p> </dd> <dt>ENILimitExceeded</dt> <dd> <p>ENI limit exceeded.</p> </dd> <dt>BadPermissionsUserCredentials</dt> <dd> <p>Unable to use the Role provided.</p> </dd> <dt>InvalidBundleRobotApplication</dt> <dd> <p>Robot bundle cannot be extracted (invalid format, bundling error, or other issue).</p> </dd> <dt>InvalidBundleSimulationApplication</dt> <dd> <p>Simulation bundle cannot be extracted (invalid format, bundling error, or other issue).</p> </dd> <dt>RobotApplicationVersionMismatchedEtag</dt> <dd> <p>Etag for RobotApplication does not match value during version creation.</p> </dd> <dt>SimulationApplicationVersionMismatchedEtag</dt> <dd> <p>Etag for SimulationApplication does not match value during version creation.</p> </dd> </dl>
        createdAt:
          allOf:
          - $ref: '#/components/schemas/CreatedAt'
          - description: The time, in milliseconds since the epoch, when the fleet was created.
      description: Support for the AWS RoboMaker application deployment feature has ended. For additional information, see https://docs.aws.amazon.com/robomaker/latest/dg/fleets.html.
    GenericString:
      type: string
      pattern: .*
      minLength: 0
      maxLength: 1024
    EnvironmentVariableMap:
      type: object
      minProperties: 0
      maxProperties: 20
      additionalProperties:
        $ref: '#/components/schemas/EnvironmentVariableValue'
    ThrottlingException: {}
    ResourceNotFoundException: {}
    DeploymentApplicationConfigs:
      type: array
      items:
        $ref: '#/components/schemas/DeploymentApplicationConfig'
      minItems: 1
      maxItems: 1
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/robomaker/
x-hasEquivalentPaths: true
